endpoint: renc.osn.xsede.org
submissions_endpoint: submit.ltreb-reservoirs.org
scores_bucket: bio230121-bucket01/vera4cast/scores
forecasts_bucket: bio230121-bucket01/vera4cast/forecasts
submissions_bucket: vera4cast-submissions
inventory_bucket: bio230121-bucket01/vera4cast/inventory
prov_bucket: bio230121-bucket01/vera4cast/prov
targets_bucket: bio230121-bucket01/vera4cast/targets
themes: daily
theme_datetime_format: ["%Y-%m-%d", "%Y-%m-%d %H:%M:%S"]
example_model_id: example
site_table: vera4cast_field_site_metadata.csv
