challenge_long_name: NEON Ecological Forecasting Challenge
project_id: neon4cast
endpoint: sdsc.osn.xsede.org
submissions_endpoint: submit.ecoforecast.org
scores_bucket: bio230014-bucket01/challenges/scores
forecasts_bucket: bio230014-bucket01/challenges/forecasts
submissions_bucket: submissions
inventory_bucket: bio230014-bucket01/challenges/inventory
prov_bucket: bio230014-bucket01/challenges/prov
targets_bucket: bio230014-bucket01/challenges/targets
archive_bucket: bio230014-bucket01/challenges/archive
model_metadata_bucket: bio230014-bucket01/challenges/metadata/model_id
model_metadata_gsheet: https://docs.google.com/spreadsheets/d/1f177dpaxLzc4UuQ4_SJV9JWIbQPlilVnEztyvZE6aSU/edit?usp=sharing
example_model_id: example
site_table: neon4cast_field_site_metadata.csv
target_metadata_gsheet: https://docs.google.com/spreadsheets/d/10YTX9ae_C1rFdLgEDkUcCRCpUkVYv06leY01BtD1BgM/edit?usp=sharing
challenge_url: https://www.neon4cast.org
github_repo: eco4cast/neon4cast-ci
variable_groups:
  Aquatics:
    variable: ['oxygen','temperature','chla']
    duration: ['P1D','P1D','P1D']
    thumbnail_link: 'https://projects.ecoforecast.org/neon4cast-catalog/img/neon_buoy.jpg'
    thumbnail_title: 'NEON Aquatics Buoy'
  Terrestrial:
    variable: ['nee','le','nee','le']
    duration: ['P1D','P1D','PT30M','PT30M']
    thumbnail_link: 'https://projects.ecoforecast.org/neon4cast-catalog/img/BONA_Twr.jpg'
    thumbnail_title: 'NEON Field Tower'
  Phenology:
    variable: ['gcc_90','rcc_90']
    duration: ['P1D','P1D']
    thumbnail_link: 'https://www.neonscience.org/sites/default/files/styles/max_1300x1300/public/image-content-images/_BFP8455.jpg'
    thumbnail_title: 'NEON Field Tower'
  Beetles:
    variable: ['abundance', 'richness']
    duration: ['P1W','P1W']
    thumbnail_link: 'https://www.neonscience.org/sites/default/files/styles/max_width_1170px/public/image-content-images/Beetles_pinned.jpg'
    thumbnail_title: 'Beetle Image'
  Ticks:
    variable: ['amblyomma_americanum']
    duration: ['P1W']
    thumbnail_link: 'https://www.neonscience.org/sites/default/files/styles/max_2600x2600/public/image-content-images/tick-image.jpg'
    thumbnail_title: 'NEON Ticks'
catalog_config:
  about_string: 'www.neon4cast.org'
  about_title: 'NEON Ecological Forecasting Challenge Documentation'
  scores_thumbnail: "https://raw.githubusercontent.com/LTREB-reservoirs/vera4cast/main/dashboard/img/banner-2.jpg"
  scores_thumbnail_title: "Falling Creek Reservoir"
  forecasts_thumbnail: "https://raw.githubusercontent.com/LTREB-reservoirs/vera4cast/main/dashboard/img/banner-2.jpg"
  forecasts_thumbnail_title: "Falling Creek Reservoir"
  forecast_path: 'catalog/forecasts/'
  scores_path: 'catalog/scores/'
  aws_download_path: 'bio230014-bucket01/challenges/forecasts/parquet/'
  host_url: "https://www.ecoforecastprojectvt.org"
  host_name: "Ecoforecast Challenge"
  bbox:
    max_lat: 71.2824
    min_lat: 17.9696
    max_lon: -66.7987
    min_lon: -156.6194
  site_type: 'MultiPoint'
  base_image_path: 'https://data.ecoforecast.org/neon4cast-catalog'
  citation_doi: "https://doi.org/10.1002/fee.2616"
  citation_text: "Thomas, R.Q., C. Boettiger, C.C. Carey, M.C. Dietze, L.R. Johnson, M.A. Kenney, J.S. Mclachlan, J.A. Peters, E.R. Sokol, J.F. Weltzin, A. Willson, W.M. Woelmer, and Challenge Contributors. 2023. The NEON Ecological Forecasting Challenge. Frontiers in Ecology and Environment 21: 112-113."
  dashboard_url: "https://www.ltreb-reservoirs.org/vera4cast"
  dashboard_title: "NEON Forecast Challenge Dashboard"
  site_metadata_url: 'https://raw.githubusercontent.com/eco4cast/neon4cast-ci/main/neon4cast_field_site_metadata.csv'
