endpoint: data.ecoforecast.org
submissions_endpoint: submit.ltreb-reservoirs.org
scores_bucket: vera4cast-scores
forecasts_bucket: vera4cast-forecasts
submissions_bucket: vera4cast-submissions
inventory_bucket: vera4cast-inventory
prov_bucket: vera4cast-prov
targets_bucket: vera4cast-targets
themes: aquatics
theme_datetime_format: "%Y-%m-%d"
example_model_id: test
site_table: vera_field_site_metadata.csv


