endpoint: sdsc.osn.xsede.org
submissions_endpoint: submit.ltreb-reservoirs.org
scores_bucket: bio230121-bucket01/vera4cast-scores
forecasts_bucket: bio230121-bucket01/vera4cast-forecasts
submissions_bucket: bio230121-bucket01/vera4cast-submissions
inventory_bucket: bio230121-bucket01/vera4cast-inventory
prov_bucket: bio230121-bucket01/vera4cast-prov
targets_bucket: bio230121-bucket01/vera4cast-targets
themes: aquatics
theme_datetime_format: "%Y-%m-%d"
example_model_id: test
site_table: vera_field_site_metadata.csv


