about_string: 'www.ltreb-reservoirs.org/vera4cast'
about_title: 'VERA Forecasting Challenge Documentation'
fcr_thumbnail: "https://raw.githubusercontent.com/LTREB-reservoirs/vera4cast/main/dashboard/img/banner-2.jpg"
forecast_path: 'catalog/forecasts/'
scores_path: 'catalog/scores/'
aws_download_path: 'bio230121-bucket01/vera4cast/forecasts/parquet/duration=P1D'
model_metadata_url: "https://docs.google.com/spreadsheets/d/1f177dpaxLzc4UuQ4_SJV9JWIbQPlilVnEztyvZE6aSU/edit?usp=sharing"
host_url: "https://ecoforecast.org"
host_name: "Ecoforecast Challenge"
bbox_max_lat: 71.2824
bbox_min_lat: 17.9696
bbox_max_lon: -66.7987
bbox_min_lat: -156.6194
site_type: 'MultiPoint'
base_image_path: 'https://data.ecoforecast.org/neon4cast-catalog'
citation_doi: "https://doi.org/10.1002/fee.2616"
citation_text: "Thomas, R.Q., C. Boettiger, C.C. Carey, M.C. Dietze, L.R. Johnson, M.A. Kenney, J.S. Mclachlan, J.A. Peters, E.R. Sokol, J.F. Weltzin, A. Willson, W.M. Woelmer, and Challenge Contributors. 2023. The NEON Ecological Forecasting Challenge. Frontiers in Ecology and Environment 21: 112-113."
