# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  #schedule:
  #  - cron: '0 12 * * *'
  workflow_dispatch:


name: baseline_generation

jobs:
  docker:
    runs-on: ubuntu-latest
    container: rocker/geospatial:latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install
        shell: Rscript {0}
        run: |
          remotes::install_github("cboettig/aws.s3")

      - name: Update GEFS
        shell: Rscript {0}
        run: |
          source("run_terrestrial_baselines.R")
