on:
  #schedule:
  #  - cron: '0 23 * * *'
  workflow_dispatch:

name: catalog_external_test2

jobs:
  metadata_catalog:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container:
      #image: eco4cast/rocker-neon4cast:latest
      image: rocker/ml-verse
      options: --memory 15120m
    steps:
      - run: git config --system --add safe.directory '*'

      - name: checkout source repository
        uses: actions/checkout@v4
        with:
           fetch-depth: 0
           set-safe-directory: '*'

      - name: Checkout destination repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          set-safe-directory: '*'
          repository: eco4cast/neon4cast-catalog # Replace with your destination repo details
          path: neon4cast-catalog
          token: ${{ secrets.PAT }} # Use the PAT from secrets

      - name: Render metadata
        shell: Rscript {0}
        run: source("catalog/model_metadata.R")

      - name: Commit and Push
        run: |
          cd destination-repo
          git config user.name github-actions
          git config user.email github-actions@github.com

          git pull
          git add .
          git commit -a -m "update catalog" || echo "nothing to commit"
          git push origin main

