on:
  #schedule:
  #  - cron: '0 23 * * *'
  workflow_dispatch:

name: catalog_external

jobs:
  metadata_catalog:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container:
      #image: eco4cast/rocker-neon4cast:latest
      image: rocker/ml-verse
      options: --memory 15120m
    steps:
      - run: git config --system --add safe.directory '*'

      - name: checkout source repository
        uses: actions/checkout@v4
        with:
           fetch-depth: 0
           set-safe-directory: '*'

      - name: Render metadata
        shell: Rscript {0}
        run: source("catalog/model_metadata.R")

      - name: Render catalog
        shell: Rscript {0}
        run: source("catalog/catalog.R")

      - name: checkout destination repository
        uses: actions/checkout@v4
        with:
           repository: eco4cast/neon4cast-catalog
           fetch-depth: 0
           set-safe-directory: '*'

      - name: Commit and Push
        run: |
          cd neon4cast-catalog
          git config user.name github-actions
          git config user.email github-actions@github.com

          mkdir catalog
          cp -r ../catalog/* ./catalog

          git pull
          git add catalog/* .
          git commit -a -m "update catalog" || echo "nothing to commit"
          git push https://${GITHUB_PAT}:${GITHUB_PAT}@github.com/eco4cast/neon4cast-catalog
