# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:


name: gefs_osn

jobs:
  docker:
    runs-on: ubuntu-latest #[self-hosted]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
      container: rocker/geospatial:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        shell: Rscript {0}
        run: |
          install.packages("remotes")
          install.packages("devtools")
          devtools::install(dependencies=TRUE, upgrade="never")
          #install.packages("remotes")
          remotes::install_github("eco4cast/gefs4cast")

      - name: Update GEFS
        shell: Rscript {0}
        run: |
          source("drivers/download_stage1.R")

      - name: Generate stage 2
        shell: Rscript {0}
        run: |
          source("drivers/generate_stage2.R")

