name: Run S3 Script

on:
  workflow_dispatch:  # allows manual run

jobs:
  r-job:
    runs-on: ubuntu-latest

    env:
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Set up R
      - uses: r-lib/actions/setup-r@v2
          
      # 3. Run your script
      - name: Run S3 Script
        run: |
          Rscript S3_Bucket_ReadWrite.R
