# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

name: scoring

jobs:
  docker:
    runs-on:  arc-runner-set
    timeout-minutes: 1440
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container: rocker/geospatial:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        shell: Rscript {0}
        run: |
          print(options("repos"))
          install.packages('arrow', repos = 'https://apache.r-universe.dev')
          remotes::install_deps(".", dep=TRUE, repos="https://cran.rstudio.com")
          remotes::install_github("eco4cast/score4cast", repos="https://cran.rstudio.com")

      - name: Generate scores
        shell: Rscript {0}
        run: |
          source("scoring/scoring.R")

      - name: Update inventory
        shell: Rscript {0}
        run: |
          source("scoring/build_score_inventory.R")
