name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: efi-cirrus
    container: 
      # IMPORTANT.  Please set a memory limit <= 45 GB.
      image: eco4cast/rocker-neon4cast:latest
      options: --memory 15g
    steps:
      # Dummy tests
      - run: sudo apt-get update && sudo apt-get -y install iproute2
      - run: ip link
      
