# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

name: target-generation

jobs:

  terrestrial:
    runs-on: efi-cirrus
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_SUBMISSIONS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SUBMISSIONS }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container:
      image: eco4cast/rocker-neon4cast:latest
      options: --memory 45g
    steps:
      - uses: actions/checkout@v3

      - name: Generate targets
        shell: Rscript {0}
        run: |
          source("targets/terrestrial_targets.R")
